#!/usr/bin/env node
/*
 * Builds the deployable copy of the deck into dist/.
 *
 * The deck is authored as one HTML file with an inline <script type="text/babel"> block, so it
 * can be opened straight from disk with no tooling. That convenience costs the viewer a 2.9 MB
 * Babel download and a full JSX compile on the main thread before the first slide appears, which
 * is the worst thing you can hand a phone. This step does the compile once, here, and ships a
 * copy that needs only React.
 *
 * Source of truth stays elevator-deck.html. Nothing is generated by hand.
 */
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const babel = require('./vendor/babel.js');

const ROOT = __dirname;
const DIST = path.join(ROOT, 'dist');
const SCRIPT_RE = /<script type="text\/babel"[^>]*>([\s\S]*?)<\/script>/;
const BABEL_TAG_RE = /[ \t]*<script src="vendor\/babel\.js"><\/script>\r?\n?/;

// Everything the deployed site needs. vendor/babel.js is deliberately absent.
const COPY = ['index.html', 'architecture-talk-ideas.html', 'README.md', 'img', 'audio',
  path.join('vendor', 'react.js'), path.join('vendor', 'react-dom.js')];

function copy(rel) {
  const from = path.join(ROOT, rel);
  if (!fs.existsSync(from)) return;
  fs.cpSync(from, path.join(DIST, rel), { recursive: true });
}

function build() {
  const srcPath = path.join(ROOT, 'elevator-deck.html');
  const html = fs.readFileSync(srcPath, 'utf8');

  const match = html.match(SCRIPT_RE);
  if (!match) throw new Error('elevator-deck.html has no <script type="text/babel"> block');
  if (!BABEL_TAG_RE.test(html)) throw new Error('elevator-deck.html does not load vendor/babel.js');

  const compiled = babel.transform(match[1], {
    presets: ['react'],
    compact: false,
    comments: false,
    sourceType: 'script',
  }).code;

  // A literal </script> anywhere in the payload would close the tag early.
  const safe = compiled.replace(/<\/script/gi, '<\\/script');

  // Function replacers, not string ones: compiled JS is full of $ sequences ($$typeof, $&, $`)
  // and String.replace would treat them as substitution patterns and corrupt the output.
  const block = '<script>\n' + safe + '\n</script>';
  let out = html.replace(SCRIPT_RE, () => block);
  out = out.replace(BABEL_TAG_RE, () => '');

  // Parse what will actually ship. A corrupted inline script is a black screen for every viewer,
  // so the build must fail here rather than let it reach Pages.
  const shipped = out.slice(out.lastIndexOf(block), out.lastIndexOf(block) + block.length)
    .replace(/^<script>\n/, '').replace(/\n<\/script>$/, '');
  if (shipped.length < 1000) throw new Error('could not find the compiled script in the output');
  new vm.Script(shipped, { filename: 'dist/elevator-deck.html' });   // throws on any syntax error

  if (/text\/babel/.test(out)) throw new Error('compiled output still references text/babel');
  if (/vendor\/babel\.js/.test(out)) throw new Error('compiled output still loads babel');
  if (!/React\.createElement/.test(out)) throw new Error('compiled output contains no React.createElement');
  if (!/DECK_ON_PAINT/.test(out)) throw new Error('compiled output lost the boot diagnostics');

  fs.rmSync(DIST, { recursive: true, force: true });
  fs.mkdirSync(DIST, { recursive: true });
  fs.writeFileSync(path.join(DIST, 'elevator-deck.html'), out);
  COPY.forEach(copy);

  const before = Buffer.byteLength(html) + fs.statSync(path.join(ROOT, 'vendor', 'babel.js')).size;
  const after = Buffer.byteLength(out);
  console.log('built dist/elevator-deck.html');
  console.log('  script to parse before first slide: ' +
    (before / 1048576).toFixed(2) + ' MB -> ' + (after / 1048576).toFixed(2) + ' MB');
}

build();
